version: "3.8"

services:
  ingest:
    container_name: ingest
    build:
      context: services/pkg/ingest
      dockerfile: services/deploy/ingest/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - elk
    environment:
      - ACCESS_SECRET=${ACCESS_SECRET}
      - ACCESS_KEY=${ACCESS_KEY}
      - CONSUMER_SECRET=${CONSUMER_SECRET}
      - CONSUMER_KEY=${CONSUMER_KEY}
    command: ["./wait-for-it.sh", "rabbitmq:15672", "--timeout=60", "--", "./ingest"]

  worker:
    container_name: worker
    build:
      context: services/pkg/worker
      dockerfile: services/deploy/worker/Dockerfile
    depends_on:
      - rabbitmq
      - ingest
    networks:
      - elk
    command: ["./wait-for-it.sh", "rabbitmq:15672", "--timeout=60", "--", "./worker"]
