version: "3.8"

services:
  ingest:
    container_name: ingest
    build:
      context: ./services
      dockerfile: deploy/ingest/Dockerfile
    env_file:
      .env

  worker:
    container_name: worker
    build:
      context: ./services
      dockerfile: deploy/worker/Dockerfile
    depends_on:
      - ingest
    env_file:
      .env
